/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BossWebcamLabRouteImport } from './routes/boss-webcam-lab'
import { Route as DeniseRouteImport } from './routes/denise'
import { Route as GaryRouteImport } from './routes/gary'
import { Route as RichardRouteImport } from './routes/richard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BossWebcamLabRoute = BossWebcamLabRouteImport.update({
  id: '/boss-webcam-lab',
  path: '/boss-webcam-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DeniseRoute = DeniseRouteImport.update({
  id: '/denise',
  path: '/denise',
  getParentRoute: () => rootRouteImport,
} as any)
const GaryRoute = GaryRouteImport.update({
  id: '/gary',
  path: '/gary',
  getParentRoute: () => rootRouteImport,
} as any)
const RichardRoute = RichardRouteImport.update({
  id: '/richard',
  path: '/richard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boss-webcam-lab': typeof BossWebcamLabRoute
  '/denise': typeof DeniseRoute
  '/gary': typeof GaryRoute
  '/richard': typeof RichardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boss-webcam-lab': typeof BossWebcamLabRoute
  '/denise': typeof DeniseRoute
  '/gary': typeof GaryRoute
  '/richard': typeof RichardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boss-webcam-lab': typeof BossWebcamLabRoute
  '/denise': typeof DeniseRoute
  '/gary': typeof GaryRoute
  '/richard': typeof RichardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boss-webcam-lab' | '/denise' | '/gary' | '/richard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boss-webcam-lab' | '/denise' | '/gary' | '/richard'
  id: '__root__' | '/' | '/boss-webcam-lab' | '/denise' | '/gary' | '/richard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BossWebcamLabRoute: typeof BossWebcamLabRoute
  DeniseRoute: typeof DeniseRoute
  GaryRoute: typeof GaryRoute
  RichardRoute: typeof RichardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss-webcam-lab': {
      id: '/boss-webcam-lab'
      path: '/boss-webcam-lab'
      fullPath: '/boss-webcam-lab'
      preLoaderRoute: typeof BossWebcamLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denise': {
      id: '/denise'
      path: '/denise'
      fullPath: '/denise'
      preLoaderRoute: typeof DeniseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gary': {
      id: '/gary'
      path: '/gary'
      fullPath: '/gary'
      preLoaderRoute: typeof GaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/richard': {
      id: '/richard'
      path: '/richard'
      fullPath: '/richard'
      preLoaderRoute: typeof RichardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BossWebcamLabRoute: BossWebcamLabRoute,
  DeniseRoute: DeniseRoute,
  GaryRoute: GaryRoute,
  RichardRoute: RichardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
